services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    # network_mode: "host"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    # network_mode: "host"
    ports:
      - "6379:6379"

  # pgadmin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
  #     PGADMIN_DEFAULT_PASSWORD: postgres

volumes:
  pg_data:

